name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: go mod download

      - name: Build application
        run: |
          cd cmd/openapi-mock
          go build -v
          cd ../..

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.51

      - name: Run tests
        run: go test -v $(go list ./... | grep -v vendor)

      - name: Code Climate Coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: go test -v ./... -coverprofile=c.out
          prefix: "github.com/muonsoft/openapi-mock"
